### ISSUE TITLE
AnsibleCredentialsResult in awx-resource-operator/roles/job_runner/tasks /create_project.yml 

### ISSUE THREAD

**Issue by the-it-jaeger** [ansible/awx-resource-operator#132]
https://github.com/ansible/awx-resource-operator/blob/f43c2c045280bae22f15cd8f432bd5ac6bebd0e8/roles/job_runner/tasks/create_project.yml#L43

I believe 'AnsibleCredentialsResult' above should be 'AnsibleProjectResult' as it is at:

https://github.com/ansible/awx-resource-operator/blob/f43c2c045280bae22f15cd8f432bd5ac6bebd0e8/roles/job_runner/tasks/create_project.yml#L56

**Comment by cooktheryan** [comment]
+1 ill throw a PR in for this. Great catch
