### ISSUE TITLE
How to run jobs from the operator

### ISSUE THREAD

**Issue by fatimazahrae2104** [ansible/awx-resource-operator#44]
Recently I deployed  Ansible AWX on my Openshift cluster, and it works fine, and I also deployed the Ansible automation platform resource operator from the OperatorHub, Then I used the Ansible JobTemplate API instance, where I mentioned all the informations of the JobTemplate i have already on my AWX.

I want to know how to launch the JobTemplate from the Operator, can anyone help me how it works?!!

Thanks in advance!

This is my JobTemplate yaml.

![image](https://user-images.githubusercontent.com/36632123/106775258-3ac89d00-6643-11eb-82df-386768b44c3d.png)

**Comment by mikeshng** [comment]
Hi, based on my understanding of your question: you want to launch a job instance for the job template you created?

- create a secret https://github.com/ansible/awx-resource-operator/blob/devel/deploy/crds/example_secret.yaml
- create an ansiblejob cr like https://github.com/ansible/awx-resource-operator/blob/devel/deploy/crds/tower.ansible.com_v1alpha1_joblaunch_cr.yaml
- make sure `inventory` and `extra_vars` have prompt on launch enabled on the awx side if you want to use those optional fields.

**Comment by fatimazahrae2104** [comment]
Hello @mikeshng, 
First of all thank you for your immediate response.

- I already created the secret where I put the awx token which I generated from https://awxhost/api/v2/tokens (can you Confirm this pls?)

- I created the Ansible Job for the job template but I don't get the output of the job as I get it on Tower.

![image](https://user-images.githubusercontent.com/36632123/106862189-0d253780-66c7-11eb-8bb4-06c600e27fb7.png)

-  here is what I Get when executing this command: `kubectl -n awx logs -f job.batch/demo-job9mn2s`

![image](https://user-images.githubusercontent.com/36632123/106862311-3f369980-66c7-11eb-9932-3847427b99d8.png)

However my Inventory contains localhost as a unique host  with Prompt on launch checked, and I don't have extra vars so I deleted this section.

- My Ansible Job

![image](https://user-images.githubusercontent.com/36632123/106862930-1a8ef180-66c8-11eb-9ae7-8d9dbce79d88.png)

**Comment by mikeshng** [comment]
Hi, this is working as expected for now.

The AnsibleJob CR triggers the job launch and gives you an overview of the result of the tower job. So if you do:
kubectl -n awx get AnsibleJob demo-job<suffixhere> -o yaml
you should see the result of the job execution. For example, if there was an error, it will show
```
status:
  ansibleJobResult:
    changed: true
    failed: false
    status: error
    url: >-
      https://ansible-tower-web-svc-tower.apps.-redacted-.com/#/jobs/playbook/5
```
Users are meant to use that url and actually see the all the details of the job execution.
Maybe you can make a feature request regarding displaying the output of the actual tower job execution log in Kubernetes log some where?

As for the secret, it should be fine since you were able to create a job and communicate with the awx/tower successfully.

**Comment by fatimazahrae2104** [comment]
Actually, it's not very important for me to display the AnsibleJob execution log using Kubernetes as long as I can see it on tower, but I just thought that I didn't follow the right steps to make them appear in kubernetes, but now it's fine :) .

- But what if I want to re-execute the Job Template, should I create another Ansible Job to do So?
- And I have another important question pls, I tried to create another job template on Tower using another Host (it's a POD created on the same namespace of the cluster), so I put the service IP Address of this POD as Host name in my inventory  but the connection is unreachable, how can i allow  connections between Tower, the operator and target hosts? should I obligatory install ssh on my target hosts, even if I use Job APIs of the operator?

**Comment by mikeshng** [comment]
> But what if I want to re-execute the Job Template, should I create another Ansible Job to do So?

Yep. Each AnsibleJob represent an instance of Job on awx/tower. It behaves similar to how awx/tower keeps a list of already ran jobs. In short, to re-execute use https://github.com/ansible/awx-resource-operator/blob/devel/deploy/crds/tower.ansible.com_v1alpha1_joblaunch_cr.yaml#L4 which should give you another instance with a unique enough suffix.

> your 2nd question

The operator does not need to communicate with your "target hosts", it only needs to talk to the tower. The tower is responsible for communicating with the various hosts that it's managing. In short, without using the operator, first make sure the Job Template can be executed successfully using your AWX/Tower instance only. Then afterwards, you can use the operator to trigger those jobs.

**Comment by fatimazahrae2104** [comment]
Hello @mikeshng 

Ok, so the role of this operator is only to trigger the jobs created on AWX, nothing else, is it?

**Comment by mikeshng** [comment]
Right, as of now, this operator is only responsible for managing job templates and creating job instances for job templates.

See the CRDs and examples that this operator deals with here: https://github.com/ansible/awx-resource-operator/tree/devel/deploy/crds

**Comment by fatimazahrae2104** [comment]
Ok, I got it now.

Thank you so much for the help 👍

**Comment by the-it-jaeger** [comment]
It would seem all questions have been answered. I would suggest /close

@fatimazahrae2104 would you confirm you are satisfied and close this issue?
