### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by PaulVerhoeven1** [ansible/awx-resource-operator#73]
Hi,

i am missing an README.md in this repo which explains what the awx-resource-operarator does and how you can run it.
Personally i don't have any clue what this repo does at this moment.

**Comment by rooftopcellist** [comment]
I have added a README.md in this PR - https://github.com/ansible/awx-resource-operator/pull/80

**Comment by rooftopcellist** [comment]
That has merged now.
